# Generated by Django 6.0.2 on 2026-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=140, unique=True, verbose_name='Slug (для URL)'),
            preserve_default=False,
        ),
    ]
