# Generated by Django 6.0.2 on 2026-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/second/', verbose_name='Второе фото'),
        ),
    ]
